In [2]:
number = input("enter first number-")
number2= input("enter second number-")
e=int(number)
t=int(number2)
z=e*t

#x=number*number2
print(z)
def x(a,b):
    c=a*b
    if (c>1000):
        c=a*b
    else:
        c=a+b
    print(c)
number3 = input("enter third number")
number4= input("enter fourth number")
e=int(number3)
t=int(number4)    
x(e,t)

enter first number-10
enter second number-25
250
enter third number65
enter fourth number54
3510


In [1]:
#prime number-range
n1=10
n2=20
for i in range(n1,n2+1):
    for j in range(2,i):
        if i%j==0:
            break
    else:
        print(i)
#prime number-single         
x=int(input("enter a number to check if its prime or not--"))
for v in range(2,x):
        if x%v==0:
            print(x,"is not prime")
            break
else:
        print(x,"is prime")

11
13
17
19


In [2]:
d=[1,2,3]
print(d)
for v in range(len(d)):
    print(d[v],end=" ")
    d[v]=2
    print(d[v])
print(d)
    
    
    

[1, 2, 3]
1 2
2 2
3 2
[2, 2, 2]


In [35]:
d=[34,34,34,34,54,44,34]
d2=[]
i=0
y=d[0]
while(y==34):
    d2.append(y)
    i=i+1
    y=d[i]
print(d2)
l=len(d2)
print(l)
    

[34, 34, 34, 34]
4


In [61]:
number=input("enter the number u want the count of")
v=int(number)

number2=input("enter the numbers in the list")
x1=int(number2)
number3=input("enter the numbers in the list")
x2=int(number3)
number4=input("enter the numbers in the list")
x3=int(number4)
d=[x1,x2,x3]
#d=[34,34,34,35,34,34,34]
c=0
f=len(d)
for i in range(f):
    if(d[i]==v):
        c=c+1
    else:
        pass
print(c)

enter the number u want the count of5
enter the numbers in the list4
enter the numbers in the list5
enter the numbers in the list5
2


In [58]:
pwd

'C:\\Users\\anime'

In [4]:
##sum of numbers in a range "a"
x=input("enter range")
a=int(x)

temp=0
for i in range(a):
    sum=i+temp
    print(i,sum)
    temp=sum

print("total sum is",sum)

enter range15
0 0
1 1
2 3
3 6
4 10
5 15
6 21
7 28
8 36
9 45
10 55
11 66
12 78
13 91
14 105
total sum is 105


In [80]:
##Split example in list
##sum example 
##average exapmle
##notes:use int(v) 

x=input("enter numbers in spaces")
x1=x.split()

sum1=0
old=0
print("All entered numbers ", x1)

for v in x1:
    sum1=int(v)+old ##use sum1+=int(v) here you can skip old mentioning "old"
    
    old =sum1

average=sum1/len(x1)
print("sum is",sum1,"average is",average)

enter numbers in spaces45 55 10
All entered numbers  ['45', '55', '10']
sum is 110 average is 36.666666666666664


In [86]:
matrixOne = [[6,9,11],
    [2 ,3,8]]

matrixTwo = [[15,18,11],
    [26,16,19]]

result = [[0,0,0],
         [0,0,0]]

# First iterate rows
for i in range(len(matrixOne)):
   # Second iterate columns
   for j in range(len(matrixOne[0])):
            result[i][j] = matrixOne[i][j] + matrixTwo[i][j]
print("Addition of two Matrix In Python")
for res in result:
    print(res)

Addition of two Matrix In Python
[21, 27, 22]
[28, 19, 27]


In [105]:
##Question 5: Given a list of numbers,
##return True if first and last number of a list is same

d=[10, 20, 30, 40, 10]

    
if(d[0]==d[-1]):
    print(True)
else:
    print(False)


True


In [5]:
#count certain number in  a user define input list
#use of function 
#use of for and if
def g():
    x=input("enter the number you want to add in a list in spaces")
    global x1
    x1=x.split()

    return x1

print(g())  ##this print() will print the return value from function    
c=0
for i in range(len(x1)):
    if(int(x1[i])==4):
        c=c+1
    else:
        pass
print(c)

enter the number you want to add in a list in spaces4 4 5 6
['4', '4', '5', '6']
2


In [7]:
##simple exapmle of a funtion and how to use return...
##return actually sends output and is visible if print is used for default funtion.
##difference between printing and not printing a function if return value is mentioned
def c(a,b):
    v=a+b
    return v
print(c(2,3))

def v():
    d=34
    return d
v()


5


34

In [111]:
##displaying even index characters in a list,string etc
list1=input("enter a string--")
x=str(list1)
for i in range(0,len(x),2):
    print(x[i])

enter a string--animesh
a
i
e
h


In [114]:
##Given a string and an integer number n, remove characters from a string starting from zero up to n and return a new string

list1=input("enter a string---")
x=str(list1)
integ=input("enter an integer")
i=int(integ)

print(x[i:])
    
    


enter a string---animesh
enter an integer2
imesh


In [115]:
##Given a list of numbers, Iterate it and print only those numbers which are divisible of 5

List1=input("enter integers in spaces")
listy=List1.split()
for v in range(len(listy)):
    if(int(listy[v])%5==0):
        print(listy[v])
    else:
        pass





enter integers in spaces10 20 32
10
20


In [117]:
##Question 7: Return the total count of sub-string “Emma” appears in the given string

List1=input("enter strings in spaces")
listy=List1.split()
c=0
for v in range(len(listy)):
    if(str(listy[v])=="Emma"):
        c=c+1
    else:
        pass
print(c)

enter strings in spacesEmma is good developer. Emma is a writer
2


In [189]:
##Print the following pattern
#1 
#2 2 
#3 3 3 
#4 4 4 4 
#5 5 5 5 5
for num in range(10):
    for i in range(num):
        print(num,end="    ") 
    print("\n")




1    

2    2    

3    3    3    

4    4    4    4    

5    5    5    5    5    

6    6    6    6    6    6    

7    7    7    7    7    7    7    

8    8    8    8    8    8    8    8    

9    9    9    9    9    9    9    9    9    



In [257]:

for num in range(6):
    for i in range(1,num):
        print(i, end=' ')
    print()



1 
1 2 
1 2 3 
1 2 3 4 


In [281]:
for num in range(6):
    for i in range(num,0,-1):
        print(i, end=' ')
    print()


1 
2 1 
3 2 1 
4 3 2 1 
5 4 3 2 1 


In [263]:
for num in range(6,0,-1):
    for i in range(1,num):
        print(i, end=' ')
    print()

1 2 3 4 5 
1 2 3 4 
1 2 3 
1 2 
1 



In [265]:
for num in range(6,0,-1):
    for i in range(num):
        print(num, end=' ')
    print()

6 6 6 6 6 6 
5 5 5 5 5 
4 4 4 4 
3 3 3 
2 2 
1 


In [279]:
for num in range(6,-1,-1):
    for i in range(num,-1,-1):
        print(2**i, end=' ')
    print()

64 32 16 8 4 2 1 
32 16 8 4 2 1 
16 8 4 2 1 
8 4 2 1 
4 2 1 
2 1 
1 


In [284]:
for num in range(6):
    for i in range(num):
        print(i*num, end=' ')
    print()


0 
0 2 
0 3 6 
0 4 8 12 
0 5 10 15 20 


In [286]:
for num in range(6):
    for i in range(num,0,-1):
        print("*", end=' ')
    print()


* 
* * 
* * * 
* * * * 
* * * * * 


In [288]:
def exponent(base, exp):
    c=base**exp
    return c
print(exponent(2,3))
    

8


In [12]:
#decimat to octal
print('%o' % 8)

10


In [22]:
#Anybase TO DECIMAL
a=int(input("enter a binary number"),2)
print(a)
b=int(input("enter a hexadecimal number"),16)
print(b)
c=int(input("enter a octal number"),8)  ## 2 WILL TELL THAT THE INTEGER/INPUT IS BINARY AND THE PRINTED FORM WILL BE IN DECIMAL FORMAT WHICH IS DEFAULT.   
print(c)


##DECIMAL TO ANY BASE
#HERE YOU CAN DEFINE A FUNCTION OR REMEBER: BINARY=BIN,OCTAL=OCT,HEXADECIMAL=HEX
c=int(bin(8)[2:])
print(c)
#using format
print (format(8, 'b'))

enter a binary number1000
8
enter a hexadecimal numberF
15
enter a octal number10
8
1000
1000


In [317]:
print('%.2f' % 458.8898)

458.89


In [337]:
#print float values using split and user input

x=input("enter numbers in spaces")
y=x.split()
for v in y:
    
     print(float(v),end=" ")


enter numbers in spaces55.5 45.69 85.36
55.5 45.69 85.36 

In [334]:
##use of string

str1,str2,str3 = input("Enter three string").split()
print(str1,str2,str3)

Enter three stringgg hh ll
gg hh ll


In [335]:
#display above data using string.format() method
#I have 1000 dollars so I can buy 3 football for 450.00 dollars.


quantity = 3
totalMoney = 1000
price = 450
statement1 = "I have {1} dollars so I can buy {0} football for {2:.2f} dollars."
print(statement1.format(quantity, totalMoney, price))

I have 1000 dollars so I can buy 3 football for 450.00 dollars.


In [12]:
x=input("enter a binary number")
c=int(x,2)  

print(c)


enter a binary number14
12


In [13]:
x=input("enter the decimal number")
print(hex(int(x)))

enter the decimal number54
0x36


In [19]:
##swap
##temp method
print("swapping of 3,4")
a,b=3,4
temp=a
a=b
b=temp
print(a,b)

##formula method

a=a+b
b=a-b
a=a-b
print(a,b)

##python method

a,b=b,a
print(a,b)

swapping of 3,4
4 3
3 4
4 3


In [34]:
##Compliment of 12

##13 second compliment is same as 12's first compliment


##BIT operators

## import math module

print(~15)

a=12
b=13
print(a & b) ##and
print(a | b) ##or
print(a ^ b) ##xor

import math
x=math.sqrt(25)
print(x)

-16
12
13
1
5.0


#Loop exercises# Loop exercises# Loop exercises# Loop exercises# Loop exercises
#Loop exercises# Loop exercises
#Loop exercises# Loop exercises# Loop exercises# Loop exercises# Loop exercises¶
#Loop exercises# Loop exercises# Loop exercises# Loop exercises# Loop exercises# Loop exercises# Loop exercises

In [1]:
i=0
while(i<=10):
    print(i)
    i=i+1


0
1
2
3
4
5
6
7
8
9
10


In [4]:
for num in range(7):
    for i in range(1,num):
        print(i,end=" ")
    print("")



1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [10]:
num=input("enter a number")
i=int(num)
sum1=0
for v in range(1,i+1):
    sum1+=v
print(sum1)
    

enter a number10
55


In [14]:
a=int(input("enter"))
for v in range(1,11):
    x=a*v
    print(x)

enter5
5
10
15
20
25
30
35
40
45
50


In [18]:
## Given a list iterate it and display numbers which are divisible by 5 and if you find number greater than 150 stop the loop iteration
#x = [12, 15, 32, 42, 55, 75, 122, 132, 150, 180, 200]



x=input("enter number in spaces")
y=x.split()
for v in y:
    if(int(v)%5==0 and int(v)<=150):
        print(v)

enter number in spaces10 150 200
10
150


In [9]:
x=input("enter a number")
x2=len(x)
print(x2)
c=0
for v in range(x2):
    c=c+1
print(c)


enter a number458524
6
6


In [16]:
for num in range(5,0,-1):
    for i in range(num,0,-1):
        print(i,end=" ")
    print()

5 4 3 2 1 
4 3 2 1 
3 2 1 
2 1 
1 


In [27]:
x=input("enter number in spaces")
y=x.split()
c=len(y)
print(c)
z=[]
for v in range(c-1,-1,-1):
    #print(y[v])
    z.append(y[v])
print(z)
    
    

enter number in spaces10 20 30
3
['30', '20', '10']


In [29]:
for i in range(5):
    print(i)
else:
    print("done!")

0
1
2
3
4
done!


In [35]:
##prime number
##my method


x=int(input("enter starting number"))
y=int(input("enter ending number"))
c=0
for v in range(x,y+1):
    for i in range(2,v):
        if(v%i!=0):
            c=c+1
        else:
            pass
        if(c==v-2):
            print(v,"is a prime number")
        else:
            pass
    c=0

        


enter starting number0
enter ending number15
3 is a prime number
5 is a prime number
7 is a prime number
11 is a prime number
13 is a prime number


In [47]:
##fibonacci series
x=0
y=1
for i in range(10):
    print(x,end=" ")
    total=x+y
    x=y
    y=total
    

0 1 1 2 3 5 8 13 21 34 

In [49]:
##multiplication table
v=10
for i in range(1,v+1):
    x=v*i
    print(x)
    

10
20
30
40
50
60
70
80
90
100


In [47]:
##factorial

i=4
b=i
v=b-1
for g in range(1,i):
    x=b*v
    v=v-1
    b=x
print(x)

##factorial using recursion

def fact(n):
    if n==0:
        return 1
    return n * fact(n-1)
print(fact(5))
    
    

24
120


In [62]:
##even position
## x[0::2] selects every second number staring with index 0
## x[1::3] selects every third number starting with index 1
x = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
for i in x[1::2]:
    print(i, end=" ")


20 40 60 80 100 

In [67]:
##sum of serries
#2+22+222+2222+22222

number_of_terms = 5
start = 2
sum = 0
for i in range(0, number_of_terms):
    print(start, end=" ")
    sum += start
    start = (start * 10) + 2
print("\nSum of above series is:", sum)

2 22 222 2222 22222 
Sum of above series is: 24690


In [8]:
def music(a,b):
    global c
    c=a+b
    return c
print(music(2,10))



12


In [34]:
##prime number
##for else
##break

x=107
for i in range(2,x):
    if(x%i!=0):
            continue
    else:        
            print(x,"it is not prime number")
            break
        
else:
        print(x,"is a prime number")
        

107 is a prime number


In [46]:
9##easy prime number

x=7
for i in range(2,7):
    if x%i == 0:
        print(x,"is not a prime number")
        break
else:
        print(x,"is a prime number")
        

7 is a prime number


In [26]:
## break 

available=10
asking=int(input("enter the number of candies you want"))
i=1
while i <= asking:
        if i>available:
            print("out of stock")
            break
        print(i,"candy mili")
        i+=1
print("get lost now")

            

        



enter the number of candies you want11
1 candy mili
2 candy mili
3 candy mili
4 candy mili
5 candy mili
6 candy mili
7 candy mili
8 candy mili
9 candy mili
10 candy mili
out of stock
get lost now


In [9]:
# continue

x=int(input("enter starting number"))
y=int(input("enter the end number"))
for i in range(x,y):
    if (i%3==0):
        continue
    print(i)


enter starting number10
enter the end number25
10
11
13
14
16
17
19
20
22
23


In [12]:
# for else
x=[12,24,32]
for i in range(len(x)):
    if x[i]%11==0:
        print("this is our number")
else:
    print("we couldn't find your number")

we couldn't find your number


In [84]:
#array

#import array as ar
from array import *

x=array('i',[-1,2,3])       #typecode-bB,h
l=len(x)  
print(x)

y=array('u',["#"])          #unicode-characters
print(y)

x.reverse()                 #this reverse is modifying array x            #method
print(x)
print(x[0])                 #prints/fetch particular element from array
print()

for i in range(l):         #prints/fetch particular element from array one by one.
    print(x[i])
print()    
for e in x:
    print(e)
print()

newarray=array(x.typecode,(a for a in x))   #copies the typecode and elements from array x
newarray1=array(x.typecode,(a*a for a in x))
print(newarray)
print(newarray1)

array('i', [-1, 2, 3])
array('u', '#')
array('i', [3, 2, -1])
3

3
2
-1

3
2
-1

array('i', [3, 2, -1])
array('i', [9, 4, 1])


In [91]:
# array input from user
#append the elements of array of desired length from user
#search the index of desired element from array
from array import *
x=array('i',[])
l=int(input("enter the length of the array"))
for i in range(l):
    k=int(input("enter the value"))
    x.append(k)                                 #append elements one by one
print(x)

search_no=int(input("enter the search value"))
print(x.index(search_no))                       #finds the index number of the desire search value

enter the length of the array4
enter the value25
enter the value48
enter the value96
enter the value36
array('i', [25, 48, 96, 36])
enter the search value96
2


In [172]:
#methods of array=reverse,append,index
from array import *
x=array("i",[1,2,3,4])
y=array(x.typecode,(a*2 for a in x))
print(x,y)
print(x[0])
x.reverse()      #method
x
z=4
x.append(z)      #method
print(x)
x.index(1)       #method

array('i', [1, 2, 3, 4]) array('i', [2, 4, 6, 8])
1
array('i', [4, 3, 2, 1, 4])


3

In [151]:
#numpy
#array([],int)
#access the element: x[0],x[10] etc
#linspace(start,stop_included,how many parts?) used to create array/vector as in matlab
#logspace(start,stop_included,parts) here the elements are 10^start,10^stop etc
#zeros(range,int_optional),
#ones(range,int_optional)
#arange(start,stop_excluded,steps)
#addition- x+5 will add 5 to each element,x+y will add two arrays.
#multiplication: x*2- will multiply each elemnt by 2.
#multiplication: x*y is element wise multiplication.
#dot(x,y)   _ it will give dot product of two arrays. ab+a2b2+a3b3...
#funtions: max(x),min(x),sum(x),sin(x),cos(x),log(x),sqrt(x),
#methods copy x=y.view() -shallow copy. meaning --changing values in y after the view command, the values in x will change as well
#methods copy x=y.copy() -deep copy -no link after command
#methods x.mean()-average,x.std()-std deviation



from numpy import *

x=array([1,2,3,4],int)
print(x.dtype)
print(x)

x=linspace(0,12,13)      
print(x)

x=ones(5,int)
print(x)

y=arange(0,12,2)
print("y=",y)

y=y+5
print('y=',y)

u=max(y)          #function
print("u=",u)

v=sqrt(y)         #function
print("v=",v)

z=v.view()         #method
print("z=",z)
z=y.copy()         #method
print("z=",z)

#-------------------------------------------------------------------------------------------------------------
#multidimensional x=array([     [],[],[],[]      ])
#access the elements: x[1,3] - 2nd row,4th column
#slicing: x[0][0:2] -1st row, 1st and 2nd column.
#multiplication x*y- element wise, dot(x,y)- actual matrix multiplication 
#x.ndim - gives dimensions of multiarray
#x.shape -gives row and column numbers in a tuple. (r,c)
#x.size -gives number of all elements...r*c
#y=x.flatten() -converts from multi-D to single-D              #method
#z=y.reshape(r,c) -converts single-D to 2D                     #method
#z1=y.reshape(no.of 2d arrays,r,c)                             #method


x=array([[1,3],[4,6],[7,9]])
print("x is",x)
print(x.ndim)
print(x.size)
print(x.shape)
y=x.flatten()
print("flattten_x is y=>",y)
z=y.reshape(2,3)
print("reshaped of y is ",z)
z=y.reshape(3,2,1)
print("3d matrix of y is",z)

#-------------------------------------------------------------------------------------------------------------
#create matrix with help of array-    m=matrix(x)                       ...where x is an array
#create matrix -                      m=matrix('1 2 3 ; 4 5 6 ; 7 8 9')
#diagonal(m)                          #funtion
#m.min() etc                          #method
#matrix multiplication                m3=m1 * m2

m=matrix(z)
print("m is=",m)
m=matrix("1 2 3;4 5 6")
print("new m is=",m)
print("diagonal of m is=",diagonal(m))
print("minimum of matrix m is",m.min())












int32
[1 2 3 4]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
[1 1 1 1 1]
y= [ 0  2  4  6  8 10]
y= [ 5  7  9 11 13 15]
u= 15
v= [2.23606798 2.64575131 3.         3.31662479 3.60555128 3.87298335]
z= [2.23606798 2.64575131 3.         3.31662479 3.60555128 3.87298335]
z= [ 5  7  9 11 13 15]
x is [[1 3]
 [4 6]
 [7 9]]
2
6
(3, 2)
flattten_x is y=> [1 3 4 6 7 9]
reshaped of y is  [[1 3 4]
 [6 7 9]]
3d matrix of y is [[[1]
  [3]]

 [[4]
  [6]]

 [[7]
  [9]]]
m is= [[1 3]
 [4 6]
 [7 9]]
new m is= [[1 2 3]
 [4 5 6]]
diagonal of m is= [1 5]
minimum of matrix m is 1


In [56]:
#funtions


def dark(a,b,d,c=10):          #formal_arguement  #2default(value of c) 
    x=a+b
    y=a-b+d
    s=a*b*c
    
    return x,y,s
    
r,t,s=dark(5,1,6)                #actual_arguement   #1position
z=dark(a=10,d=5,b=50)            #3keyword
print("r=",r,"t=",t,"s=",s)
print("z=",z)
print()

#4variable_length
def var(a,*b):
    c=a
    for i in b:
        c=c+i
    return c
x=var(5,6,7,8)    
print("x=",x)
 #or
def var(*b):
    c=0
    for i in b:
        c=c+i
    print(c)
var(5,6,7,8)
print()


#5keyword+variable  
#use of ** in variable length to accept keyword data in dictionary
#x=globals()["a"]
nigga="black person"
def info(name,**data):
    nigga="best friend"
    x=globals()["nigga"]
    print(x)
    print(name)
    print(data)
info("aman",age=12,city="nagpur")


##pass list to a function
#even,odd example


def count(lst):
    even_count=0
    odd_count=0
    for i in lst:
        if i%2==0:
            even_count+=1
        else:
            odd_count+=1
    return even_count,odd_count
#x=input("enter the names in spaces")
#x1=x.split()
lst=[23,45,33,21,20,88,86,54,64]
even,odd=count(lst)
print("even is {} and odd is {}".format(even,odd))


##anonymous funtions-lambda
f= lambda a:a*a
print("anonymous funtion is {}".format(f(4)))

## filter,map,reduce
from functools import reduce
nums=[1,2,3,4,5,6,7,8,9]
evens=list(filter(lambda n:n%2==0,nums))         #filter using lambda function
print(evens)

doubles=list(map(lambda n:n*n,evens))            #map using lambda funcction
print(doubles)



def add_all(a,b):
    return a+b   
sums=reduce(add_all,doubles)                     #reduce using simple function
print(sums)

animesh jaiswal
r= 6 t= 10 s= 50
z= (60, -35, 5000)

x= 26
26

black person
aman
{'age': 12, 'city': 'nagpur'}
even is 5 and odd is 4
anonymous funtion is 16
[2, 4, 6, 8]
[4, 16, 36, 64]
120


In [57]:
print(__name__)

__main__


In [82]:
##oops
##class-design of a phone -it has attributes(what i know?) and behaviour/methods/funtion (what i'll be doing?)
##object is an instance of a class. 1000s (objects)of phones having same design(class)

class computer:
    smartphone="yes"                  #variable defined outside init are class variables. 
    def __init__(self,a,b):           #variable defined in init are called instance variable    #instance method
        self.a=a
        self.b=b
        self.jaan="symbian"
        #print("this is innit")
        self.inn=self.inner()         #defining object inn having class inner
        
    def config(self):                                                                          #instance method
        print("16gb memory,","240 gb disk,","48 mega pixel camera,",self.a,self.b,self.jaan)
    
    def compare_b(self,other):       #compare two objects                                      #instance method
        if self.b==other.b:
            return True
        else:
            return False 
     
    def get_a(self):                 ##get/accessor                                            #instance method
        return self.a
    def set_a(self,newvalue):        ##setter/mutator                                          #instance method
        self.a=newvalue
    @classmethod    
    def info(cls):                                                                             #class method
        return cls.smartphone
     
    @staticmethod                                                                              #static method
    def stat():
        print("Static methods have a limited use case because, like class methods or any other methods within a class, they cannot access the properties of the class itself. However, when you need a utility function that doesn't access any properties of a class but makes sense that it belongs to the class, we use static functions...this is static method example. It doesn't require any parameter to pass.As you can see,stat is empty. no self and no cls")
    
    
    #inner class 
    class inner:
        
        def __init__(self):
            self.cam="not 48"
                
                
        def inner_method(self):
            print(self.cam,",this is from inner class")

            
            
            
            
            
            
            
            
class computer5():                                     #just another class
    def __init__(self,a,b):
        super().__init__(a,b)
        self.ever="computer_1" 
    def mett_1(self):
        print("this is class_5")                
        
class computer2(computer):                              #single level inheritance A->B
    def __init__(self,a,b):
        super().__init__(a,b)      #this will inherit init of super class first i.e A. Then inherit itself.
        self.i="jessica"
    def mett2(self):
        print("this is class2")
        
class computer3(computer2):                             #multi level inheritance A->B->C
    def mett3(self):
        print("this is class3")
        
class computer4(computer5,computer):                   #multiple inheritance (A,B)->C
    def __init__(self,a,b):
        super().__init__(a,b)
    
    def mett4(self):
        print("this is class4")
    
c3=computer3(45,5)                               #A->B->C......But c2 will try to find init of subclass first(computer3).
print(c3.a,c3.i)

c4=computer4(23,76)
print(c4.a,c4.mett_1(),c4.ever)           #init of only first class will be inherited in multiple.    c4.ever will not work.
print()
   
c2=computer2(34,22)        
print(c2.i)                
                
                
                
                
motorola=computer(1,4)
nokia=computer(3,4)
print(nokia.a)
print(motorola.a)
print()

#computer.config(motorola)                        #another method to call a method of object
motorola.config()
nokia.config()
print()


print(nokia.jaan)
motorola.jaan="android"
print(motorola.jaan)
print()


print(nokia.smartphone)
nokia.smartphone="no"
print(nokia.smartphone,motorola.smartphone)      #changing nokia.smartphone to "no"
computer.smartphone="kya"
print(nokia.smartphone,motorola.smartphone)      #even after changing computer.smartphone to"kya" we gets nokia's as :"no" 
nokia=computer(3,4)                              #thats why we reassign again the nokia to class computer
print(nokia.smartphone)
print()
 
    
##compare
if(motorola.compare_b(nokia)):                   #comapre_b is a method and we are passing another object nokia.
    print("they are same")    
else:
    print("they are different")

    
##accessors and mutator methods
print(motorola.get_a())
motorola.set_a(3)
print(motorola.a)
print()


##cls and class variable execution

print(computer.info())
print()


##staticmethod
print(computer.stat())
print(nokia.stat())
print()


##inner
print(nokia.inn.cam)
print(nokia.inn.inner_method())

45 jessica
this is class_5
23 None computer_1

jessica
3
1

16gb memory, 240 gb disk, 48 mega pixel camera, 1 4 symbian
16gb memory, 240 gb disk, 48 mega pixel camera, 3 4 symbian

symbian
android

yes
no yes
no kya
kya

they are same
1
3

kya

Static methods have a limited use case because, like class methods or any other methods within a class, they cannot access the properties of the class itself. However, when you need a utility function that doesn't access any properties of a class but makes sense that it belongs to the class, we use static functions...this is static method example. It doesn't require any parameter to pass.As you can see,stat is empty. no self and no cls
None
Static methods have a limited use case because, like class methods or any other methods within a class, they cannot access the properties of the class itself. However, when you need a utility function that doesn't access any properties of a class but makes sense that it belongs to the class, we use static fun

In [66]:
class A(object):
    def __init__(self):
        print("Entering A")
        super(A, self).__init__()
        print("Leaving A")

class B(object):
    def __init__(self):
        print("Entering B")
        super(B, self).__init__()
        print("Leaving B")

class C(A, B):
    def __init__(self):
        print("Entering C")
        A.__init__(self)
        B.__init__(self)
        print("Leaving C")
c=C()
print(c)

Entering C
Entering A
Entering B
Leaving B
Leaving A
Entering B
Leaving B
Leaving C


In [15]:
#iterators


x=[1,2,3]
it=iter(x)

print(next(it))
print(it.__next__())
print(next(it))
print("")


#generators-----it is a function that will give u an iterator

def gen():        
    yield 1
    yield 2
    yield 3
x=gen()
print(next(x))
print(x.__next__())
print(next(x))
print("")

#exception handling

a=5
b=0

try:
    print(a/b)
except Exception:
    print("no,cannot do that")
finally:
    print("closed")


1
2
3

1
2
3

no,cannot do that
closed


In [75]:
##file handling---use rb,wb for img files.(read/write binary-r/w b)
 
#open in read
f=open('doc.txt','r')
g=open("doc2.txt","r")
print(f.read())
print("")


#create in write
h=open("doc2.txt","w")
h.write("this is tommy shelby ")
h.write("this is my home")

for data in g:
    print(data)
#print(g.readline())
#print(g.readline())




this is arthur fucking shelby
by the orders of peaky blinders
this hotel is ours
understande mate?
do you understand?

this is tommy shelby this is my home


In [77]:
#copy file data
f=open('doc.txt','r')
k=open("doc3.txt","w")
for data in f:
    k.write(data)

In [27]:
##linear search
##sort using sorted(x)
##buble sort
x=[1,2,3,4,5,6,7,8,0]
n=6
d=sorted(x)
print(d)

##using loop
for i,v in enumerate(x):
    if v==n:
        print("found at",i+1)
        break
    else:
        continue

    print("not found")
    
##using function    
def search(x,n):
    for i,v in enumerate(x):
        if v==n:
                print("found at",i+1)
                break
        else:
              continue
        print("not found")
search(x,5);

##bubble sort

x=[5,4,6,7,2,1,8]
for i in range(len(x)-1,0,-1):
    for j in range(i):
        if x[j]<x[j+1]:
            x[j],x[j+1]=x[j+1],x[j]   #swapping
            #temp=x[j]
            #x[j]=x[j+1]
            #x[j+1]=temp
        else:
            pass
print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8]
found at 6
found at 5
[8, 7, 6, 5, 4, 2, 1]


In [2]:
#polymorphism
#duck typing

class main_code1():              ## 3 main codes(classes),all having execute function.
    def execute(self):
         print("this is bus1")
j=main_code1()                  ##defining ide 

class main_code2():
    def execute(self):
        print("this is bus2")
k=main_code2()

class main_code3():
    def execute(self):
        print("this is bus3")
l=main_code3()


class laptop():               ## our object related class having ide and execute function.
    def code(self,ide):       ##code funtion will recieve ide(object of other classes including codes to execute)
        ide.execute()         ##running the execute code
x=laptop()

print(x.code(j))             ##running 3 different codes using same object x
print(x.code(k))
print(x.code(l))


this is bus1
None
this is bus2
None
this is bus3
None


In [135]:
#operator overloading
# __add__ , __str__, __gt__ etc
class just():
    
    def __init__(self,m,n):
        self.m=m
        self.n=n
    def __add__(self,other):
        x=self.m+other.m
        y=self.n+other.n
        s=just(x,y)
        return s
    
    def __gt__(self,other):
        x=self.m+self.n
        y=other.m+other.n
        if x>y:
            return True
        else:
            False
            
    def __str__(self):
        return "{} {}".format(self.m, self.n)
        
            
e=just(58,69)
t=just(60,65)
u= e+t
print(u.m) 
print(u.n)

print(e>t)   #__gt__
print(e)     #__str__

118
134
True
58 69


In [151]:
##pandas

from pandas import *
y = 'TopSellingAlbums.csv'         #storing path in a variable
x=read_csv(y)                     #function read_csv("path of csv")   ##here for excel use read_excel("path of excel")
print(x.head())                          #by default prints first five rows


z=x[["Length","Artist"]]                #created a new df using existing df x,here mention the headers name of column. 
print(z)



            Artist                      Album  Released   Length  \
0  Michael Jackson                   Thriller      1982  0:42:19   
1            AC/DC              Back in Black      1980  0:42:11   
2       Pink Floyd  The Dark Side of the Moon      1973  0:42:49   
3  Whitney Houston              The Bodyguard      1992  0:57:44   
4        Meat Loaf            Bat Out of Hell      1977  0:46:33   

                         Genre  Music Recording Sales (millions)  \
0               pop, rock, R&B                              46.0   
1                    hard rock                              26.1   
2             progressive rock                              24.2   
3               R&B, soul, pop                              27.4   
4  hard rock, progressive rock                              20.6   

   Claimed Sales (millions) Released.1 Soundtrack  Rating  
0                        65  30-Nov-82        NaN    10.0  
1                        50  25-Jul-80        NaN     9.5  
2 

In [167]:
##pandas
##create DataFrame using dictionary and DataFrame() funtion
from pandas import *
songs={"Band":["Linkin Park","AC/DC","One Direction"], "MembersCount":[4,5,6],"Total Songs":[21,43,56]}
x=DataFrame(songs)
print(x.head())
print("")

print(x.iloc[0,2],"___this is output for iloc(row,column)")
print(x.loc[0,"Band"],"___this is output for loc(row,header name)")
print("")

z=x.iloc[0:2,0:2]                ##iloc doesn't include last term
print(z)
print("")

z1=x.loc[0:2,"Band":"MembersCount"]   ##loc includes last term
print(z1)

            Band  MembersCount  Total Songs
0    Linkin Park             4           21
1          AC/DC             5           43
2  One Direction             6           56

21 ___this is output for iloc(row,column)
Linkin Park ___this is output for loc(row,header name)

          Band  MembersCount
0  Linkin Park             4
1        AC/DC             5

            Band  MembersCount
0    Linkin Park             4
1          AC/DC             5
2  One Direction             6


In [7]:
from numpy import *
x=array([[1,3],[4,6],[7,9]])
x.reshape(1,-1)

array([[1, 3, 4, 6, 7, 9]])